### ISSUE TITLE
How to use FANOVA?

### ISSUE THREAD

**Issue by haytham918** [reliable-ai/fairml-multiverse#2]
Hello,

I am wondering how you guys use the FANOVA. Looks like they are using "float" for their code but it has been removed from numpy since 1.20. FANOVA stopped updating its code a long time ago. I am not sure what I shall do in this case.

**Comment by jansim** [comment]
Hello Haytham,

Sorry for the slow response, somehow I missed this issue.

It's indeed a shame that the FANOVA package seems to be discontinued. We got it to work by carefully choosing the right versions of dependencies (including choosing a slightly older Python version), so that they play nice with each other. I would suggest to create a virtual environment (e.g. pipenv, as we use here, but there are also many alternatives for Python) and set it up such that the FANOVA package has the correct versions of packages to work well in there.

You can see the exact versions of packages that we ended up using in here: https://github.com/reliable-ai/fairml-multiverse/blob/main/Pipfile.lock.

I hope this helps with your issue?

**Comment by haytham918** [comment]
Hi Jan,

Thank you for the response. I actually got this working a while ago, and no doubt it was quite painful.

I do want to ask if you have any recommendations of techniques that can conduct an efficient sweep/analysis of the impact on model performance/fairness due to different decision choices?

Best,
Haytham

**Comment by jansim** [comment]
In our paper, we saw that running the FANOVA over a random subset of the multiverse works well to identify important design decisions, this is described in [3.2.1](https://dl.acm.org/doi/fullHtml/10.1145/3630106.3658974#sec-16).

[![Figure 9 from the paper.](https://dl.acm.org/cms/attachment/html/10.1145/3630106.3658974/assets/html/images/facct24-89-fig9.jpg)](https://dl.acm.org/doi/fullHtml/10.1145/3630106.3658974#fig9)

This may be sufficient for your use case? It's not the same as quantifying the impact of choices, however. But if you get an idea of which decisions are important, you could look at them in more detail.
